var data={
        "name":"zxj",//名称
        "qq":"1601022696",//qq号码
        "logo":"http://qlogo3.store.qq.com/qzone/1601022696/1601022696/100",//qq号码获取头像
        "em":"1601022696@qq.com",//电子邮件
        "motto":"这是条懒狗，什么都没有写...",//座右铭
        "iy":"XXX开发工程师",//职业
        "jl":"https://orangeyunczy.github.io/an/cv.docx",//简历地址
        "list":[//首页文章
            {
                "href":"./images/bodyer/b1.jpg",
                "title":"蘑菇丁自动上班打卡签到",
                "bodyer":"服务器部署蘑菇丁自动打开脚本，设定好每日时间自动打开用户，打卡接口均为蘑菇丁官方打卡接口。",
                "url":"http://www.mogudinko.top",
                "date":"2020-12-15"
            }
        ],
        "like":[//首页推荐文章
            {
                "href":"./images/bodyer/l1.jpg",
                "title":"http获取qq头像功能API",
                "bodyer":"知道qq号码的情况下通过http请求，调用接口抓取qq头像图片",
                "url":"https://www.jianshu.com/p/22170ca50ccb"
            }
        ]
};